name: PHP tests

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:

  validate-composer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.1]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php-version }}

    - name: Validate composer.json and composer.lock
      uses: php-actions/composer@master
      with:
        php_version: ${{ matrix.php-version }}
        command: validate

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.1]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@master
        with:
          php_version: ${{ matrix.php-version }}

      - name: Run phpstan
        run: vendor/bin/phpstan analyse -c phpstan.neon

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.1 ]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@master
        with:
          php_version: ${{ matrix.php-version }}

      - name: Run unit tests
        run: php -v && vendor/bin/phpunit -c phpunit.xml
